name: Test OS

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      pytest-args:
        required: false
        type: string
        default: ''
      lxml:
        required: false
        type: string
        default: '[""]'
      include:
        required: false
        type: string
        default: '[]'

jobs:
  test:
    name: Test (python-${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.lxml != '' && 'lxml' || 'no-lxml' }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        python-version: ${{ fromJson(inputs.python-version) }}
        lxml: ${{ fromJson(inputs.lxml) }}
        include: ${{ fromJson(inputs.include) }}

    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup locales
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo locale-gen en_US.UTF-8
        sudo locale-gen de_DE.UTF-8
        sudo update-locale
    - name: Install dependencies
      run: uv sync --group dev
    - name: Test
      run: >
        uv run
        ${{ matrix.lxml != '' && '--with lxml' || '' }}
        pytest
        ${{ inputs.pytest-args }}
        --junit-xml=test-results-py${{ matrix.python-version }}-${{ matrix.lxml != '' && 'lxml' || 'xml' }}.xml
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: Test Results (Python ${{ matrix.python-version }}, ${{ matrix.os }}, ${{ matrix.lxml != '' && 'lxml' || 'no-lxml' }})
        path: test-results-py*-*.xml
