name: Test whl

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
      include:
        required: false
        type: string
        default: '[]'

jobs:
  test:
    name: Test whl (python-${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        python-version: ${{ fromJson(inputs.python-version) }}
        include: ${{ fromJson(inputs.include) }}

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download Binaries
      uses: actions/download-artifact@v4
      with:
        name: Binaries
        path: dist/
    - name: Run junitparser CLI
      run: |
        wheel=$(echo dist/junitparser-*.whl)
        uv run --with "$wheel" junitparser verify tests/data/no_fails.xml
        uv run --with "$wheel" --with lxml junitparser verify tests/data/no_fails.xml
